[package]
name = "trying-rust"
version = "0.1.0"
authors = ["blnkspace <helloworld@aviral.me>"]
edition = "2018"

[[bin]]
name = "executable"
path = "src/addition.rs"
 
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
